# $player - 玩家名称
# $reason - 封禁理由（自动生成）
ban-method: "ban $player 1d $reason"

# 模块开关设置
modules:
  Fly: true
  Crasher: true

  # 通过一些垃圾逻辑检测EMPv2攻击
  # 添加homoac.bypass.attack权限以放通特定玩家
  AntiAttack: false

  # 杂项移动
  MovementMisc: true

command:
  # 管理员运行analyse时显示目标玩家IP地址
  show-player-ip: false
